"""
Script summary:
Shared Hugging Face / torch inference helpers for comment-level ML features with
explicit CPU, Apple MPS, or CUDA device routing. Used by `scripts/compute_comment_features.py`
and inlined in `notebooks/colab_compute_comment_features_gpu.ipynb` (regenerated by
`scripts/_gen_colab_standalone_nb.py`) for standalone Colab GPU runs.

Functions provide pipeline construction, batched classification and emotion scores,
and perplexity computation with device-consistent tensor placement.
"""

from __future__ import annotations

from typing import Any, Dict

import math

import pandas as pd


def resolve_inference_device(device_arg: str) -> str:
    """
    Function summary: map CLI device flag to concrete backend string in {cpu,mps,cuda}.

    Parameters:
    - device_arg: one of auto, cpu, mps, cuda.

    Returns:
    - Canonical device string usable by loaders below; cuda falls back to cpu if unavailable.
    """
    if device_arg == "cpu":
        return "cpu"
    if device_arg == "mps":
        return "mps"
    if device_arg == "cuda":
        try:
            import torch

            return "cuda" if torch.cuda.is_available() else "cpu"
        except Exception:
            return "cpu"
    if device_arg == "auto":
        try:
            import torch

            if torch.cuda.is_available():
                return "cuda"
            if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
                return "mps"
        except Exception:
            pass
        return "cpu"
    return "cpu"


def pipeline_device_argument(device: str) -> Any:
    """
    Function summary: translate canonical device string to transformers `pipeline(device=...)`.

    Parameters:
    - device: cpu, mps, or cuda.

    Returns:
    - Value accepted by `transformers.pipeline` device argument (-1 for CPU, 0 for first CUDA GPU, or "mps").
    """
    if device == "cpu":
        return -1
    if device == "mps":
        return "mps"
    if device == "cuda":
        return 0
    return -1


def maybe_load_transformers_pipeline(task: str, model_id: str, device: str) -> Any:
    """
    Function summary: lazily build a text-classification pipeline or return None on failure.

    Parameters:
    - task: Hugging Face pipeline task name.
    - model_id: model repo id or path; empty string skips load.
    - device: canonical cpu|mps|cuda.

    Returns:
    - Pipeline instance or None.
    """
    if not model_id:
        return None
    try:
        from transformers import pipeline

        dev = pipeline_device_argument(device)
        return pipeline(task, model=model_id, truncation=True, device=dev)
    except Exception:
        return None


def label_score_as_ai_probability(result: Dict[str, Any]) -> float:
    """
    Function summary: convert one text-classification label dict to normalized AI probability.

    Parameters:
    - result: dict with `label` and `score` keys from a classifier.

    Returns:
    - Probability in [0, 1] representing AI-like class probability for aligned metrics.
    """
    label = str(result.get("label", "")).lower()
    score = float(result.get("score", 0.0))
    if "human" in label or label.endswith("0"):
        return float(max(0.0, min(1.0, 1.0 - score)))
    return float(max(0.0, min(1.0, score)))


def batch_text_classification_scores(pipe: Any, texts: list[str], batch_size: int) -> list[float]:
    """
    Function summary: batched text classification returning one probability per input text.

    Parameters:
    - pipe: transformers pipeline or None.
    - texts: comment bodies (already truncated upstream if needed).
    - batch_size: batch size for pipeline.

    Returns:
    - List of floats parallel to texts; NaN on batch failure rows.
    """
    if pipe is None:
        return [float("nan")] * len(texts)
    out: list[float] = []
    for start in range(0, len(texts), max(1, int(batch_size))):
        batch = texts[start : start + max(1, int(batch_size))]
        try:
            results = pipe(batch, truncation=True, batch_size=max(1, int(batch_size)))
            if isinstance(results, dict):
                results = [results]
            out.extend([label_score_as_ai_probability(r) for r in results])
        except Exception:
            out.extend([float("nan")] * len(batch))
    return out


def batch_emotion_scores(pipe: Any, texts: list[str], batch_size: int) -> Dict[str, list[float]]:
    """
    Function summary: batched emotion multi-label classification for four target labels.

    Parameters:
    - pipe: emotion pipeline or None.
    - texts: input strings.
    - batch_size: pipeline batch size.

    Returns:
    - Dict mapping anger, fear, sadness, surprise to score lists aligned with texts.
    """
    keys = ["anger", "fear", "sadness", "surprise"]
    scores: Dict[str, list[float]] = {k: [] for k in keys}
    if pipe is None:
        for k in keys:
            scores[k] = [float("nan")] * len(texts)
        return scores
    for start in range(0, len(texts), max(1, int(batch_size))):
        batch = texts[start : start + max(1, int(batch_size))]
        try:
            results = pipe(batch, truncation=True, batch_size=max(1, int(batch_size)), top_k=None)
            if results and isinstance(results[0], dict):
                results = [[r] for r in results]
            for row_result in results:
                row_map = {k: 0.0 for k in keys}
                for item in row_result:
                    label = str(item.get("label", "")).lower()
                    value = float(item.get("score", 0.0))
                    if label in row_map:
                        row_map[label] = value
                for k in keys:
                    scores[k].append(row_map[k])
        except Exception:
            for k in keys:
                scores[k].extend([float("nan")] * len(batch))
    return scores


def init_perplexity_components(model_id: str, device: str) -> tuple[Any, Any]:
    """
    Function summary: load tokenizer and causal LM for perplexity on the requested device.

    Parameters:
    - model_id: causal LM id or empty to skip.
    - device: cpu, mps, or cuda.

    Returns:
    - (tokenizer, model) or (None, None) on failure.
    """
    if not model_id:
        return None, None
    try:
        from transformers import AutoModelForCausalLM, AutoTokenizer

        tokenizer = AutoTokenizer.from_pretrained(model_id)
        model = AutoModelForCausalLM.from_pretrained(model_id)
        if device == "cuda":
            model = model.to("cuda")
        elif device == "mps":
            model = model.to("mps")
        else:
            model = model.to("cpu")
        model.eval()
        return tokenizer, model
    except Exception:
        return None, None


def batch_perplexity(texts: list[str], tokenizer: Any, model: Any, batch_size: int, device: str) -> list[float]:
    """
    Function summary: batched perplexity from causal LM logits with truncation and masking.

    Parameters:
    - texts: input strings.
    - tokenizer: Hugging Face tokenizer or None.
    - model: causal LM or None.
    - batch_size: micro-batch size.
    - device: cpu, mps, or cuda for tensor placement.

    Returns:
    - Per-sequence perplexity floats; NaN on errors.
    """
    if tokenizer is None or model is None:
        return [float("nan")] * len(texts)
    try:
        import torch
    except Exception:
        return [float("nan")] * len(texts)

    target = "cuda" if device == "cuda" else ("mps" if device == "mps" else "cpu")
    out: list[float] = []
    for start in range(0, len(texts), max(1, int(batch_size))):
        batch = texts[start : start + max(1, int(batch_size))]
        try:
            enc = tokenizer(
                batch,
                return_tensors="pt",
                truncation=True,
                padding=True,
                max_length=128,
            )
            enc = {k: v.to(target) for k, v in enc.items()}
            with torch.no_grad():
                outputs = model(**enc, labels=enc["input_ids"])
                logits = outputs.logits
            shift_logits = logits[:, :-1, :].contiguous()
            shift_labels = enc["input_ids"][:, 1:].contiguous()
            loss_fct = torch.nn.CrossEntropyLoss(reduction="none")
            token_losses = loss_fct(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))
            token_losses = token_losses.view(shift_labels.size())
            if "attention_mask" in enc:
                mask = enc["attention_mask"][:, 1:].contiguous()
                seq_loss = (token_losses * mask).sum(dim=1) / mask.sum(dim=1).clamp(min=1)
            else:
                seq_loss = token_losses.mean(dim=1)
            batch_ppl = torch.exp(seq_loss).detach().cpu().tolist()
            out.extend([float(v) for v in batch_ppl])
        except Exception:
            out.extend([float("nan")] * len(batch))
    return out


def append_ml_columns_to_records(
    records: list[Dict[str, Any]],
    texts: list[str],
    model_config: Dict[str, str],
    device: str,
    batch_size: int,
) -> None:
    """
    Function summary: run all configured ML models and mutate records with score columns in place.

    Parameters:
    - records: list of row dicts with join keys already set; must align index-wise with texts.
    - texts: truncated comment strings for inference.
    - model_config: detector_primary, detector_secondary, hostility, emotion, perplexity ids.
    - device: canonical cpu|mps|cuda.
    - batch_size: inference batch size.

    Returns:
    - None; records are updated with ML fields and model id metadata.
    """
    detector_primary_pipe = maybe_load_transformers_pipeline(
        "text-classification", model_config["detector_primary"], device
    )
    detector_secondary_pipe = maybe_load_transformers_pipeline(
        "text-classification", model_config["detector_secondary"], device
    )
    hostility_pipe = maybe_load_transformers_pipeline("text-classification", model_config["hostility"], device)
    emotion_pipe = maybe_load_transformers_pipeline("text-classification", model_config["emotion"], device)
    ppl_tokenizer, ppl_model = init_perplexity_components(model_config["perplexity"], device)

    primary_ai = batch_text_classification_scores(detector_primary_pipe, texts, batch_size=batch_size)
    secondary_ai = batch_text_classification_scores(detector_secondary_pipe, texts, batch_size=batch_size)
    hostility_scores = batch_text_classification_scores(hostility_pipe, texts, batch_size=batch_size)
    emotion_scores = batch_emotion_scores(emotion_pipe, texts, batch_size=batch_size)
    ppl_scores = batch_perplexity(texts, ppl_tokenizer, ppl_model, batch_size=batch_size, device=device)

    for idx, record in enumerate(records):
        record["detector_primary_ai_prob"] = float(primary_ai[idx]) if idx < len(primary_ai) else float("nan")
        record["detector_primary_human_score"] = (
            float(1.0 - primary_ai[idx]) if idx < len(primary_ai) and pd.notna(primary_ai[idx]) else float("nan")
        )
        record["detector_secondary_ai_prob"] = float(secondary_ai[idx]) if idx < len(secondary_ai) else float("nan")
        record["detector_secondary_human_score"] = (
            float(1.0 - secondary_ai[idx]) if idx < len(secondary_ai) and pd.notna(secondary_ai[idx]) else float("nan")
        )
        record["hostility_score"] = float(hostility_scores[idx]) if idx < len(hostility_scores) else float("nan")
        record["emotion_anger"] = float(emotion_scores["anger"][idx])
        record["emotion_fear"] = float(emotion_scores["fear"][idx])
        record["emotion_sadness"] = float(emotion_scores["sadness"][idx])
        record["emotion_surprise"] = float(emotion_scores["surprise"][idx])
        record["perplexity"] = float(ppl_scores[idx]) if idx < len(ppl_scores) else float("nan")
        record["log_perplexity"] = (
            float(math.log(record["perplexity"])) if pd.notna(record["perplexity"]) and record["perplexity"] > 0 else float("nan")
        )
        record["detector_primary_model_id"] = model_config["detector_primary"]
        record["detector_secondary_model_id"] = model_config["detector_secondary"]
        record["hostility_model_id"] = model_config["hostility"]
        record["emotion_model_id"] = model_config["emotion"]
        record["perplexity_model_id"] = model_config["perplexity"]
        record["device_used"] = device
